/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by TanStack Router

import { rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

export const routeTree = rootRoute.addChildren([
  IndexImport,
])

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "routes/__root.tsx",
      "children": [
        {
          "filePath": "routes/index.tsx",
          "path": "/"
        }
      ]
    }
  }
}
ROUTE_MANIFEST_END */
